version: 2021.109.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
configuration: Release
clone_depth: 1
build_script:
- cmd: >-
    dotnet build osu.Desktop -c Release -r win-x64

    dotnet build osu.Desktop -c Release -r linux-x64
test: off
artifacts:
- path: ./osu.Desktop/bin/Release/netcoreapp3.1/linux-x64
  name: osu-linux
- path: ./osu.Desktop/bin/Release/netcoreapp3.1/win-x64
  name: osu-win